version: '3.8'
services:
  your_container:
    image: curlimages/curl
    tty: true
    container_name: your_container
    entrypoint: "/bin/sh -c"
    command: '"tail -f /dev/null"'
    environment:
      http_proxy: vpnproxy:8118
      https_proxy: vpnproxy:8118

  vpnproxy:
    image: haugene/transmission-openvpn:latest
    container_name: vpnproxy
    cap_add:
      - NET_ADMIN
    # ports:
    #   - "8901:8118"
    environment:
      - OPENVPN_USERNAME=$OPENVPN_USERNAME
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
      - OPENVPN_CONFIG=$OPENVPN_CONFIG
      - OPENVPN_PROVIDER=$OPENVPN_PROVIDER
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8118
    restart: always
